### ISSUE TITLE
Error when creating new jupyterlab 3 notebook "No such file or directory: '/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/v4/nbformat.v4.5.schema.json'"

### ISSUE THREAD

**Issue by costrouc** [jupyter/nbformat#206] opened 2021-01-14 20:15 UTC
When creating a notebook in jupyterlab 3. Maybe an issue in 2 as well? This looks to be due to the nbformat release 5.1.0 and 5.1.1 which don't have the json included.

```
Traceback (most recent call last):
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 202, in post
    yield self._new_untitled(path, type=type, ext=ext)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/notebook/services/contents/handlers.py", line 154, in _new_untitled
    model = yield maybe_future(self.contents_manager.new_untitled(path=path, type=type, ext=ext))
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 397, in new_untitled
    return self.new(model, path)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/notebook/services/contents/manager.py", line 416, in new
    model['content'] = new_notebook()
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/v4/nbbase.py", line 164, in new_notebook
    validate(nb)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/v4/nbbase.py", line 39, in validate
    return validate(node, ref=ref, version=nbformat)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/validator.py", line 268, in validate
    for error in iter_validate(nbdict, ref=ref, version=version,
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/validator.py", line 303, in iter_validate
    validator = get_validator(version, version_minor, relax_add_props=relax_add_props)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/validator.py", line 57, in get_validator
    schema_json = _get_schema_json(v, version=version, version_minor=version_minor)
  File "/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/validator.py", line 94, in _get_schema_json
    with open(schema_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/jupyterlab/lib/python3.8/site-packages/nbformat/v4/nbformat.v4.5.schema.json'
jlab_core.a281a8e968046385c1ce.js:2:882629
```

**Comment by costrouc** [comment] 2021-01-14 20:20
Temporary workaround pinning to `5.0.8` fixed the issue

**Comment by MSeal** [comment] 2021-01-14 22:41
Thanks for reporting -- it looks like the Manifest did not include the schema files as it should when it got built on release. I'll look into getting this patched as soon as I am able to.

**Comment by goanpeca** [comment] 2021-01-14 22:45
Should we revert the include data on the setup.py ?

Maybe it was a regression on wheel or something that got fixed on a newer version?

**Comment by MSeal** [comment] 2021-01-14 23:01
it's also missing from the tar.gz so something removed the json schema in our changes to make the github actions work

**Comment by goanpeca** [comment] 2021-01-14 23:03
@blink1073 gave me some pointers.

Will open a Pr

**Closed** 2021-01-14 23:29 UTC

**Comment by goanpeca** [comment] 2021-01-15 00:16
@costrouc, just made a new release 5.1.2 

https://pypi.org/project/nbformat/

Could you check :) ?

**Comment by MSeal** [comment] 2021-01-15 00:28
I yanked the older releases that were invalid so people don't run into them

**Comment by yymao** [comment] 2021-01-15 00:57
@goanpeca I encountered the same issue, and 5.1.2 indeed fixes it. Thank you.

**Comment by goanpeca** [comment] 2021-01-15 01:07
Awesome @yymao!

Thanks for testing :)

**Comment by bollwyvl** [comment] 2021-01-15 02:54
Thanks for the quick action, folks. :heart: 

Over on conda-forge, 5.1.0 was marked broken:
- https://github.com/conda-forge/admin-requests/pull/216
and 5.1.2 should be up (and have some tests) soon:
- https://github.com/conda-forge/nbformat-feedstock/pull/23
